---
title: Jason Wai
logo: "/images/me-50x50.jpg"
description: Jason Wai's Blog on privacy, law, technology
baseurl: ''
url: ''
author:
  name: Jason Wai
  bio: Hi, my name is Jason Wai. I'm passionate about all things privacy. Thank you
    for visiting my blog.
twitter: https://twitter.com/jasonawai
linkedin: https://ca.linkedin.com/in/jason-wai
facebook: ''
dribbble: ''
instagram: ''
pinterest: ''
email: ''
hero: true
hero-title: Jason Wai
hero-subtitle: Privacy. Law. Technology.
hero-image: "/images/main-750x500.jpg"
footer-image: "/images/footer-750x450.jpg"
disqus-identifier: ''
google-analytics: ''
mailchimp: ''
markdown: kramdown
permalink: pretty
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll/tagging
paginate: 4
paginate_path: "/page/:num"
defaults:
- scope:
    path: _pages
  values:
    permalink: "/:basename:output_ext"
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty
include:
- _pages
sass:
  sass_dir: _sass
  style: compressed
